import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SSI
 */
public class CourseSearch extends java.awt.Frame {

    /**
     * Creates new form CourseSearch
     */
    public CourseSearch() {
        initComponents();
        setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField5 = new java.awt.TextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Code");
        add(label1);
        label1.setBounds(80, 60, 90, 30);
        add(textField1);
        textField1.setBounds(190, 60, 170, 30);

        button1.setLabel("Search");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(400, 60, 80, 30);

        label2.setText("Title");
        add(label2);
        label2.setBounds(80, 140, 50, 20);

        label3.setText("Subject");
        add(label3);
        label3.setBounds(80, 190, 60, 20);

        label4.setText("Dur");
        add(label4);
        label4.setBounds(80, 240, 24, 20);

        label5.setText("Fees");
        add(label5);
        label5.setBounds(80, 290, 32, 20);
        add(textField2);
        textField2.setBounds(190, 140, 170, 20);
        add(textField3);
        textField3.setBounds(190, 190, 170, 20);
        add(textField4);
        textField4.setBounds(190, 240, 170, 20);
        add(textField5);
        textField5.setBounds(190, 290, 170, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
        //calling a rest-api-to-search-a-code
        String id=textField1.getText();
        String endPoint="http://localhost:8080/REST-Example/course/json/"+id;
        try{
            URL url=new URL(endPoint);
            URLConnection ucon=url.openConnection();
            //obtaining an InputStream to read the result send by server
            InputStream is=ucon.getInputStream();
            
            String res="";
            
            BufferedReader br=new BufferedReader(new InputStreamReader(is));
            
            while(true){
                String line=br.readLine();
                if(line==null)break;
                res=res+line;
            }
            
            System.out.println(res);
            //we will parse this json-string
            
            JSONObject json=new JSONObject(res);
            int code=json.getInt("code");
            String title=json.getString("title");
            String subject=json.getString("subject");
            int duration=json.getInt("duration");
            int fees=json.getInt("fees");
            textField2.setText(title);
            textField3.setText(subject);
            textField4.setText(String.valueOf(duration));
            textField5.setText(String.valueOf(fees));
            
            
            
        }
        catch(Exception e){
                
         }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseSearch().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    // End of variables declaration//GEN-END:variables
}
